FROM quay.io/rockylinux/rockylinux:9 as repos
FROM quay.io/centos-bootc/centos-bootc:stream10 as builder

RUN rm -rf /etc/yum.repos.d/*

COPY --from=repos /etc/yum.repos.d/*.repo /etc/yum.repos.d/

COPY --from=repos /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9 /etc/pki/rpm-gpg

COPY 9/rockylinux-.yaml /usr/share/doc/bootc-base-imagectl/manifests/

RUN /usr/libexec/bootc-base-imagectl build-rootfs --reinject --manifest=rocky-9 /target-rootfs

###

FROM scratch

COPY --from=builder /target-rootfs/ /

LABEL containers.bootc 1
LABEL ostree.bootable 1
LABEL org.opencontainers.image.vendor Rocky Linux Foundation
LABEL org.opencontainers.image.description Rocky Linux Bootable Container Image
RUN bootc container lint --fatal-warnings
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
