#!/bin/bash
# Generate a NoCloud cloud-init seed ISO for an Omni+Dex bootc VM.
#
# The VM's hostname is baked into the seed; at first boot cloud-init sets
# it, and omni-bootstrap.service picks it up via `hostname -f` to populate
# cert SANs, Omni advertised URLs, and Dex issuer/redirect URIs.
#
# Usage:
#   scripts/make-seed.sh --hostname lab1 [--domain local] \
#     [--ssh-key ~/.ssh/id_ed25519.pub] [--password admin:changeme] \
#     [--ip 192.168.1.10/24 --gateway 192.168.1.1 --dns 1.1.1.1] \
#     [--out PATH]
#
# If --out is omitted, the ISO is written to
#   /var/lib/libvirt/images/<hostname>-seed.iso (requires sudo).
set -euo pipefail

HOSTNAME_=""
DOMAIN=local
SSH_KEY="${HOME}/.ssh/id_ed25519.pub"
PASSWORD="admin:changeme"
IP=""
GATEWAY=""
DNS=""
OUT=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --hostname) HOSTNAME_=$2; shift 2;;
    --domain)   DOMAIN=$2;    shift 2;;
    --ssh-key)  SSH_KEY=$2;   shift 2;;
    --password) PASSWORD=$2;  shift 2;;
    --ip)       IP=$2;        shift 2;;
    --gateway)  GATEWAY=$2;   shift 2;;
    --dns)      DNS=$2;       shift 2;;
    --out)      OUT=$2;       shift 2;;
    -h|--help)  sed -n '2,18p' "$0"; exit 0;;
    *) echo "error: unknown argument: $1" >&2; exit 2;;
  esac
done

[[ -n $HOSTNAME_ ]] || { echo "--hostname is required" >&2; exit 2; }
[[ -f $SSH_KEY ]]   || { echo "ssh key not found: $SSH_KEY" >&2; exit 2; }

OUT=${OUT:-/var/lib/libvirt/images/${HOSTNAME_}-seed.iso}
OUT_DIR=$(dirname "$OUT")
[[ -d $OUT_DIR ]] || mkdir -p "$OUT_DIR" 2>/dev/null || sudo mkdir -p "$OUT_DIR"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

USER_NAME=${PASSWORD%%:*}
USER_PASS=${PASSWORD#*:}

cat > "$WORK/meta-data" <<EOF
instance-id: ${HOSTNAME_}-$(date +%s)
local-hostname: ${HOSTNAME_}
EOF

cat > "$WORK/user-data" <<EOF
#cloud-config
# Generated by scripts/make-seed.sh -- do not edit by hand.
hostname: ${HOSTNAME_}
fqdn: ${HOSTNAME_}.${DOMAIN}
manage_etc_hosts: true

users:
  - name: ${USER_NAME}
    groups: [wheel]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - $(cat "$SSH_KEY")

chpasswd:
  expire: false
  users:
    - name: ${USER_NAME}
      password: ${USER_PASS}
      type: text

ssh_pwauth: true
EOF

FILES=("$WORK/user-data" "$WORK/meta-data")

if [[ -n $IP ]]; then
  [[ -n $GATEWAY ]] || { echo "--gateway is required with --ip" >&2; exit 2; }
  DNS_LIST="${DNS:-1.1.1.1}"
  cat > "$WORK/network-config" <<EOF
version: 2
ethernets:
  enp1s0:
    dhcp4: false
    addresses: [${IP}]
    routes:
      - to: default
        via: ${GATEWAY}
    nameservers:
      addresses: [${DNS_LIST}]
EOF
  FILES+=("$WORK/network-config")
fi

# Write the ISO (requires genisoimage or xorrisofs).
SUDO=""; [[ -w $OUT_DIR ]] || SUDO=sudo
$SUDO genisoimage -quiet -output "$OUT" \
  -volid cidata -joliet -rock "${FILES[@]}"

echo "Seed ISO: $OUT"
echo "  hostname: ${HOSTNAME_}.${DOMAIN}"
echo "  user:     ${USER_NAME}"
echo "  key:      ${SSH_KEY}"
if [[ -n $IP ]]; then
  echo "  network:  ${IP} via ${GATEWAY} dns ${DNS_LIST}"
fi
